apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-tomcat-deployment
  labels:
    app: sample-tomcat-application
spec:
  selector:
    matchLabels:
      app: sample-tomcat-application
  replicas: 2    
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
      
  template:
    metadata:
      labels:
        app: sample-tomcat-application
    spec:
      containers:
        - name: sample-tomcat-application
          image: kishanth1994/samplewebapp:{DOCKER_TAG}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "300Mi"
              cpu: "450m"
